production: false
timezone: America/New_York
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "lax_spacing", "superscript", "with_toc_data"]
permalink: /:year/:month/:day/:title
exclude:
- Gemfile
- Gemfile.lock
- README.txt
- tidy.conf
- config.ru
- tasks
- bin
- public
- tmp
host: metaskills.net
